import jsPDF from "jspdf";
import type { Project } from "@shared/schema";

export function generatePDF(project: Project) {
  const doc = new jsPDF();
  
  // Set up fonts and colors
  const primaryColor = [34, 102, 221]; // Blue
  const textColor = [30, 30, 30];
  const mutedColor = [120, 120, 120];
  
  let yPos = 20;
  
  // Header
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...primaryColor);
  doc.text("PROJECT QUOTATION", 20, yPos);
  
  yPos += 15;
  
  // Project Info
  doc.setFontSize(10);
  doc.setTextColor(...mutedColor);
  doc.text("Project Title:", 20, yPos);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textColor);
  doc.text(project.projectTitle, 60, yPos);
  
  yPos += 7;
  
  if (project.clientName) {
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...mutedColor);
    doc.text("Client:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...textColor);
    doc.text(project.clientName, 60, yPos);
    yPos += 7;
  }
  
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...mutedColor);
  doc.text("Date:", 20, yPos);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textColor);
  doc.text(new Date(project.createdAt).toLocaleDateString("id-ID"), 60, yPos);
  
  yPos += 15;
  
  // Line separator
  doc.setDrawColor(...mutedColor);
  doc.setLineWidth(0.5);
  doc.line(20, yPos, 190, yPos);
  
  yPos += 10;
  
  // Pricing Breakdown
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...primaryColor);
  doc.text("PRICING BREAKDOWN", 20, yPos);
  
  yPos += 10;
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...mutedColor);
  doc.text("Base Cost:", 20, yPos);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textColor);
  doc.text(`Rp ${parseFloat(project.baseCost).toLocaleString("id-ID")}`, 150, yPos, { align: "right" });
  
  yPos += 7;
  
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...mutedColor);
  doc.text("Complexity Multiplier:", 20, yPos);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(...textColor);
  doc.text(`${parseFloat(project.complexityMultiplier).toFixed(2)}x`, 150, yPos, { align: "right" });
  
  yPos += 10;
  
  // Total
  doc.setLineWidth(0.3);
  doc.line(20, yPos, 190, yPos);
  
  yPos += 8;
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...textColor);
  doc.text("TOTAL PRICE:", 20, yPos);
  doc.setFontSize(16);
  doc.setTextColor(...primaryColor);
  doc.text(`Rp ${parseFloat(project.finalPrice).toLocaleString("id-ID")}`, 190, yPos, { align: "right" });
  
  yPos += 15;
  
  // Complexity Ratings
  if (project.complexityRatings) {
    doc.setLineWidth(0.5);
    doc.line(20, yPos, 190, yPos);
    yPos += 10;
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...primaryColor);
    doc.text("COMPLEXITY ANALYSIS", 20, yPos);
    
    yPos += 10;
    
    doc.setFontSize(9);
    const ratings = project.complexityRatings as Record<string, number>;
    Object.entries(ratings).forEach(([key, value]) => {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...mutedColor);
      const label = key.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase());
      doc.text(label + ":", 20, yPos);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...textColor);
      doc.text(`${value}/10`, 150, yPos, { align: "right" });
      yPos += 6;
    });
    
    yPos += 5;
  }
  
  // Notes
  if (project.quotationNotes) {
    yPos += 5;
    doc.setLineWidth(0.5);
    doc.line(20, yPos, 190, yPos);
    yPos += 10;
    
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...primaryColor);
    doc.text("NOTES", 20, yPos);
    
    yPos += 8;
    
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...textColor);
    const splitNotes = doc.splitTextToSize(project.quotationNotes, 170);
    doc.text(splitNotes, 20, yPos);
  }
  
  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFontSize(8);
  doc.setTextColor(...mutedColor);
  doc.text("Generated by PriceRight - Videographer Pricing Tool", 105, pageHeight - 10, { align: "center" });
  
  // Save the PDF
  const fileName = `Quotation_${project.projectTitle.replace(/\s+/g, "_")}_${new Date().getTime()}.pdf`;
  doc.save(fileName);
}
